[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 1, 1]
duration = 6

[[section]]
contact  = [1, 1, 1, 1]
duration = 8
